#!/bin/bash

savefile=output.png

argumentManager () {

  #check for options
  if [[ $1 == "-s" || $1 == "-save" ]]
  then

    if (( $# > 1 ))
    then
      savefile=$2
      shift 2
      
    else
      echo "Incorrect Usage."
      echo "The save option requires a name to be specified."
      exit 1
      
    fi
  fi

  # Check for image
  if (( $# != 1 ))
  then

    echo "Invalid usage / syntax."
    echo "...repaint [options] <image>"
    exit 1
    
  elif [[ -f $1 ]]
  then

    python3 repaint.py $savefile $1
    shift 1
    exit 0

  else

    echo "Could not find file '$1'!"
    exit 1

  fi
}

while (( $# != 0 ))
do
  argumentManager $@

  if [[ $? == 1 ]]
  then
    break
  fi

  shift 2

done

